# Generated by Django 4.0.2 on 2022-09-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='ID_question',
            new_name='ID',
        ),
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.CharField(default='0000000', max_length=200, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='questions',
            name='category',
            field=models.CharField(default=0, max_length=50, verbose_name='category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=200, verbose_name='question'),
        ),
    ]
