# Generated by Django 4.0.2 on 2022-09-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_id_question_questions_id_questions_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(max_length=200, verbose_name='answer'),
        ),
    ]
