# Generated by Django 4.0.2 on 2022-09-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_questions_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='good_answer',
            field=models.CharField(default=111111, max_length=200, verbose_name='good_answer'),
            preserve_default=False,
        ),
    ]
