# Generated by Django 4.0.2 on 2022-10-17 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_questions_good_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='answer',
        ),
    ]
