# Generated by Django 4.0.2 on 2023-02-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_questions_max_points_to_get'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='max_points_to_get',
            field=models.IntegerField(default=1, verbose_name='max_points_to_get'),
        ),
    ]
