# Generated by Django 4.2 on 2023-05-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_questions_max_points_to_get'),
    ]

    operations = [
        migrations.CreateModel(
            name='changelog',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='test', max_length=20, verbose_name='title')),
                ('info', models.TextField(max_length=500, verbose_name='info')),
            ],
        ),
    ]
