# Generated by Django 4.2 on 2023-05-02 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 2, 20, 33, 57, 753815)),
        ),
    ]
