# Generated by Django 4.2 on 2023-05-02 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_changelog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelog',
            name='date',
        ),
        migrations.AddField(
            model_name='changelog',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 2, 20, 35, 5, 289045)),
        ),
    ]
