# Generated by Django 4.0.2 on 2023-05-02 20:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_changelog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 2, 20, 53, 31, 665152, tzinfo=utc)),
        ),
    ]
