# Generated by Django 4.0.2 on 2023-05-02 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_alter_changelog_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelog',
            name='timestamp',
        ),
    ]
