# Generated by Django 4.0.2 on 2023-05-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_alter_changelog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='isNew',
            field=models.BooleanField(default=True),
        ),
    ]
