# Generated by Django 4.2 on 2023-09-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_changelog_isnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordBotRequests',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.TextField(default='test discord info', max_length=100, verbose_name='info')),
            ],
        ),
    ]
