# Generated by Django 4.2 on 2023-09-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_discordbotrequests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordbotrequests',
            name='ID',
        ),
        migrations.AlterField(
            model_name='discordbotrequests',
            name='info',
            field=models.TextField(default='test discord info', verbose_name='info'),
        ),
        migrations.AddField(
            model_name='discordbotrequests',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
